# Generated by Django 5.1.7 on 2025-09-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
