# Generated by Django 5.1.7 on 2025-09-26 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_mechanic",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=255)),
                ("shop_address", models.TextField()),
                ("shop_latitude", models.FloatField(blank=True, null=True)),
                ("shop_longitude", models.FloatField(blank=True, null=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the mechanic has been verified by an admin.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFFLINE", "Offline"),
                            ("ONLINE", "Online"),
                            ("WORKING", "Working"),
                        ],
                        default="OFFLINE",
                        help_text="The mechanic's current availability status.",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanic_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("details", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mechanic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="users.mechanic",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
