# Generated by Django 5.1.7 on 2025-10-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_is_mechanic_mechanic_servicerequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_mechanic",
        ),
    ]
