# Generated by Django 5.1.7 on 2025-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_is_mechanic"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanic",
            name="KYC_document",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL to the generated legal agreement PDF.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="adhar_card",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
