# Generated by Django 5.1.7 on 2025-10-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_mechanic_kyc_document_mechanic_adhar_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanic",
            name="current_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mechanic",
            name="current_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ServiceRequest",
        ),
    ]
