# Generated by Django 5.2.7 on 2025-10-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
