# Generated by Django 5.2.11 on 2026-02-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='vehical_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
