# Generated by Django 5.2.11 on 2026-02-22 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_servicerequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRCInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20, unique=True)),
                ('license_plate', models.CharField(max_length=20)),
                ('chassis_number', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_model', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('cubic_capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('cylinders', models.IntegerField(blank=True, null=True)),
                ('seating_capacity', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_age', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_category', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_class', models.CharField(blank=True, db_column='class', max_length=100, null=True)),
                ('norms', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_count', models.CharField(blank=True, max_length=10, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('registration_date', models.CharField(blank=True, max_length=50, null=True)),
                ('rc_status', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('is_financed', models.CharField(blank=True, max_length=10, null=True)),
                ('financer', models.CharField(blank=True, max_length=255, null=True)),
                ('noc_details', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicle_rc_info',
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehical_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.vehiclercinfo', to_field='vehicle_id')),
            ],
            options={
                'db_table': 'user_vehicles',
                'unique_together': {('user', 'vehicle')},
            },
        ),
    ]
