# Generated by Django 5.2.6 on 2025-09-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatabaseCache",
            fields=[
                (
                    "cache_key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
                ("expires", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Database Cache",
                "verbose_name_plural": "Database Caches",
                "db_table": "my_cache_table",
                "managed": False,
            },
        ),
    ]
