# Generated by Django 5.2.7 on 2025-12-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(max_length=500)),
                ('link_url', models.URLField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('offer_title', models.CharField(max_length=100)),
                ('offer_subtitle', models.CharField(max_length=255)),
                ('offer_price', models.CharField(max_length=100)),
                ('bg_gradient', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
